# Generated by Django 5.2.7 on 2025-12-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_edicion', '0003_alter_articulo_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='apuntes_archivos/')),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
