# Generated by Django 5.2.7 on 2025-12-10 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_edicion', '0004_apunte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tecnicatura en Programación', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Calendario Académico',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.AlterModelOptions(
            name='apunte',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Apunte', 'verbose_name_plural': 'Apuntes'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='apunte',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apunte',
            name='tipo',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('parcial', 'Parcial'), ('final', 'Final'), ('tp', 'TP'), ('otro', 'Otro')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='bajada',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apunte',
            name='archivo',
            field=models.FileField(upload_to='apuntes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Programación I', max_length=200)),
                ('año', models.PositiveIntegerField(default=1)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_edicion.carrera')),
            ],
        ),
        migrations.AlterField(
            model_name='apunte',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_edicion.materia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
